### ISSUE TITLE
Documentation: Molang, clarification on functions inputs

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#113]
The following queries require input or inputs, the documentation doesn't show well enough if what the syntax looks like

A simple addition of parentheses could suffice.
for example

query.approx_eq -> `query.approx_eq(<n>, <m>)`

The following queries have inputs:

- [ ] query.all_tags
- [ ] query.any_tag
- [ ] query.approx_eq
- [ ] query.armor_color_slot
- [ ] query.armor_material_slot
- [ ] query.armor_texture_slot
- [ ] query.block_property
- [ ] query.camera_distance_range_lerp
- [ ] query.camera_rotation
- [ ] query.debug_output
- [ ] query.equipped_item_all_tags
- [ ] query.equipped_item_any_tag
- [ ] query.equipped_item_is_attachable
- [ ] query.get_actor_info_id
- [ ] query.get_default_bone_pivot
- [ ] query.get_equiped_item_name
- [ ] query.get_locator_offset
- [ ] query.get_root_locator_offset
- [ ] query.has_any_family
- [ ] query.has_armor_slot
- [ ] query.has_biome_tag
- [ ] query.has_block_property
- [ ] query.head_x_rotation
- [ ] query.head_y_rotation
- [ ] query.is_item_equipped
- [ ] query.item_is_charged
- [ ] query.item_slot_to_bone_name
- [ ] query.last_frame_time
- [ ] query.lod_index
- [ ] query.log
- [ ] query.maximum_frame_time
- [ ] query.minimum_frame_time
- [ ] query.noise
- [ ] query.position
- [ ] query.position_delta
- [ ] query.rotation_to_camera

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39e2f3cb-b70a-1f3b-b399-de78d15dd487
* Version Independent ID: 8955263e-956f-7ecf-d86b-5acdd6bf5fd6
* Content: [Query Functions](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/molangreference/examples/molangconcepts/queryfunctions#feedback)
* Content Source: [creator/Reference/Content/MolangReference/Examples/MolangConcepts/QueryFunctions.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/MolangReference/Examples/MolangConcepts/QueryFunctions.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
I will add this suggestion to our rewriting of the Molang reference docs.

**Comment by seeit360** [comment]
[https://learn.microsoft.com/en-us/minecraft/creator/reference/content/molangreference/examples/molangconcepts/queryfunctions](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/molangreference/examples/molangconcepts/queryfunctions)

documentation:
**equipped_item_any_tag**
Takes a slot name followed by _any tag_ you want to check for in the form of 'tag_name' and returns 0 if none of the _tags_ are on that equipped item or 1 if _at least 1 tag_ exists.

single and plural used in the same description? confusing.

so... `equipped_item_any_tag(slot,???array???)`
e.g 
**tags example**
`query.equipped_item_any_tag('slot.weapon.mainhand',['minecraft:is_armor','minecraft:arrow',...]) == 1.0` 

**tag example**
`query.equipped_item_any_tag('slot.weapon.mainhand','minecraft:is_armor') == 1.0`  

(translates to "has an item that matches an entry in the the corresponding array or singlet that contains a tag we are looking for" Right? Anyway, today is 2/1/2023 and this issue was initially filed on 8/12/20**21** and still no update.

I'd love to see a few improvements on the Minecraft documents side. I've been at this a month now and would sure like not to have to add _interpreting_ what the original document writer intended to share, with the descriptions of functions nearly identical to the name of the function, but without any context to _usage_ or _form_. That's not a document that assists or validates a developers assumptions. That's a 20 questions guessing game where I ask "how does it work" and you answer "it is the equipped item any tag" query. :)

**Comment by ofunny** [comment]
A very valid criticism indeed, I sadly spend more time on interpreting bad Molang and Bedrock wiki entries through trial and error than actually working on my project. One would at least expect parameter and return description, but yeah, no ...

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
