### ISSUE TITLE
GameTest Documentation Categorization

### ISSUE THREAD

**Issue by ReallyFatYoshi** [MicrosoftDocs/minecraft-creator#214]
**Is your feature request related to a problem? Please describe.**
The documentation for gametest is a mess. It isn't categorized at all, beta docs are mixed in with current docs.

**Describe the solution you'd like**
The solution for this problem would be to categorize beta features and current features separately.

**Describe alternatives you've considered**
There are none.

**Additional context**
Categorizing the beta and current released docs, classes, methods, functions ect. Wouldn't only help me but a lot of other people. Because we're getting very confused with the doc layout atm. Like we don't know anymore which classes are for what version because of the layout the docs has atm.

**Comment by kakinnun** [comment]
Thank you for your comment. For the GameTest docs we've made the decision to focus on documenting the latest Beta since the feature is in experimental and evolving rapidly. As the API set gets more final, the issue of the docs being out of sync between beta and stable should get better, and once the feature moves out of experimental, we will likely focus only on stable documentation. If you are interested in the GameTest experimental feature, it's highly recommended you do so on the Beta release to stay up to date with API changes and the most accurate documentation.

Currently the best way to determine API differences between versions would be to look at changelogs found here:

Beta: https://feedback.minecraft.net/hc/en-us/sections/360001185332
Release: https://feedback.minecraft.net/hc/en-us/sections/360001186971

The Bedrock Addons Discord community has also been incredibly helpful for folks as our API changes have been pretty big. Developers from the GameTest team tend to signal these changes in the **gametest** channel there and the community has helped us get this information out to a wider group.

Sorry for the confusion, but thank you for your interest in this feature. We should see less breaking API changes in 2022 as we move this feature closer to release.

As for categorizing beta vs. release documentation. We'll evaluate options here, including allowing community sites to pull reference docs for gametest.
