### ISSUE TITLE
Boat documentation

### ISSUE THREAD

**Issue by PrograMistV2** [MicrosoftDocs/minecraft-creator#26]
I want to create a new boat model and animation, but nowhere is there a render controller for it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c82d0fe-0439-313c-9ed8-16ec67bf8644
* Version Independent ID: c91a80b8-bf7a-881d-4dfc-d082745473a9
* Content: [Client Entity JSON Introduction](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/cliententitydocumenation/cliententitydocumentationintroduction)
* Content Source: [creator/Reference/Content/EntityReference/Examples/ClientEntityDocumenation/ClientEntityDocumentationIntroduction.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/ClientEntityDocumenation/ClientEntityDocumentationIntroduction.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by kakinnun** [comment]
Hi there,

We are unable to document this because this feature is currently not available in the game! If you'd like to propose new features such as creating custom boats and animations, the right forum for that would be here: https://feedback.minecraft.net/hc/en-us

I've made a note of this to pass along, but submitting an idea suggestion at https://feedback.minecraft.net/hc/en-us would be the official channel for these sorts of requests.
