### ISSUE TITLE
Uploading World fails with "Something went wrong communicating with the server" message.

### ISSUE THREAD

**Issue by rkrmpg** [MicrosoftDocs/minecraft-creator#286]
**Describe the bug**
Attempting to upload .zip file thru chunker.app containing world from Minecraft Bedrock edition version 1.18.2.
.ZIP file size is 535.3 MB

**To Reproduce**
1. Go to 'chunker.app' web site.
2. Click on 'Upload Archive'
3. Window pops to navigate to folder where file is located.
4. Selected .ZIP file that contains world.
5. Ready To Upload appears on web page.
6. Press "Start Upload" button.
7. "Uploading World" progress bar appears.
8. Progression gets to approximately 99% and error screen pops with "oops" message and  "Something went wrong communicating with the server" message.

**Expected behavior**
Attempting to upload Bedrock world in order to convert to Java.
I have also attempted to upload using the "Choose world folder" as well as using compressed file with .mcworld extention.
I have been able to successfully upload and convert other worlds.

**Desktop (please complete the following information):**
I have used Windows 10 as well as OSX 12.2 with current versions of Chrome, Safari and Edge browsers with the same inability to have a successful upload.

 [https://drive.google.com/file/d/1gal6g818yTH2aUuqUkFZ-31kyq5HHe3l/view?usp=sharing](url)

**Comment by clankstar** [comment]
Hi there,

As Chunker is a web-based service we have to limit the maximum size of uploaded worlds, which is currently at 500MB (which is slightly lower than your world). Whilst we have increased this limit a few times in the past, we currently have no set date of when we plan to exceed 500MB.

We do plan to improve this error message, so that it is clearer why this is happening rather than a generic error. Apologies for the trouble!

**Comment by kakinnun** [comment]
Closing as this as per the Chunker team response.
