### ISSUE TITLE
"minecraft: " prefix in sidebar TOC makes it difficult to read individual elements

### ISSUE THREAD

**Issue by kakinnun** [MicrosoftDocs/minecraft-creator#41]
Suggest removing "minecraft:" prefix on reference items to improve readability of sidebar nav.

**Comment by SirLich** [comment]
I think that this is *one* of a few ways to address sidebar readability. 

Another suggestion was to add some kind of 'every-other' styling, to make the wrapped-components more readable. The current wrapping is hard to read:
![image](https://user-images.githubusercontent.com/18729296/122474685-dd1a6900-cfc3-11eb-8ce0-48bb2c68a90b.png)

Removing `minecraft:` is really only useful if it keeps the lines from wrapping. If the lines still wrap, its actually maybe a step *backwards*, since it would remove the clarity of where a line begins (if it doesn't begin with `minecraft:` you know its wrapped).

But like I said at the top, the real winner here would be styling like this:
![image](https://user-images.githubusercontent.com/18729296/122474865-1521ac00-cfc4-11eb-8145-cd964179f387.png)

**Comment by v-josjones** [comment]
Addressing in Hotfix #1 
Components, Attributes, Events, Properties and Triggers will no longer have the `minecraft:` on the TOC. 
AI Goals will retain the `behavior.` in the TOC for the time being due to overlapping and similar names (i.e. breed vs breedable)

**Comment by SirLich** [comment]
I would keep the `behavior.` for more than the "time being".

I think it would cause a lot of confusion to remove it.

**Comment by mardb** [comment]
Addressed in [Hotfix for R17: Caves and Cliffs: Part 1](https://github.com/MicrosoftDocs/minecraft-creator-pr/pull/189#event-4930380792)
