### ISSUE TITLE
chunker upload fail

### ISSUE THREAD

**Issue by uyvv** [MicrosoftDocs/minecraft-creator#437]
Oops, Failed to connect to backend
Something went wrong communicating with the server.

**Comment by FormallyMyles** [comment]
Do you have further information on when this happens / steps you did? Otherwise providing your browser would be useful / world size.

**Comment by Fabrimat** [comment]
It's happening since a while to me too, but sigthly different.
When I upload a .zip file containing a directory, containing Java world files it says "The uploaded ZIP could not be accessed.". The zip file is about 160MB (so maybe that's the problem, but it never happened with other maps with about 140MB).
If I extract the zip and upload the world as directory everything works fine.

**Comment by FormallyMyles** [comment]
> It's happening since a while to me too, but sigthly different. When I upload a .zip file containing a directory, containing Java world files it says "The uploaded ZIP could not be accessed.". The zip file is about 160MB (so maybe that's the problem, but it never happened with other maps with about 140MB). If I extract the zip and upload the world as directory everything works fine.

That error means that the server can't read the ZIP you're uploading, I would recommend using the built-in folder uploader or trying different software to create the ZIP.

**Comment by kakinnun** [comment]
Closing as the Chunker team has responded with a suggestion to fix.
