### ISSUE TITLE
[Suggestion]Multilingual Support

### ISSUE THREAD

**Issue by toka7290** [MicrosoftDocs/minecraft-creator#47]
Are there any plans to make this great document available in other languages for all Minecraft creators?
For example, Japanese, Chinese, French, and other languages that are supported by Minecraft.

**Comment by kakinnun** [comment]
We are evaluating translating our documentation into other languages. It's something we want to do, but nothing to announce yet.

**Comment by kakinnun** [comment]
We now publish articles and tutorials in:
•    de-DE
•    es-MX
•    fr-FR
•    it-IT
•    ja-JP
•    ko-KR
•    zh-CN
We are looking forward to evolving our multilingual offering here. Thank you for the suggestion! Sorry it took so long to fulfill. :)

**Comment by MiemieMethod** [comment]
> We now publish articles and tutorials in: • de-DE • es-MX • fr-FR • it-IT • ja-JP • ko-KR • zh-CN We are looking forward to evolving our multilingual offering here. Thank you for the suggestion! Sorry it took so long to fulfill. :)

Could I ask for any chance to edit these translations by community? I see the translating style of the current translations is almost the same with the translations in Bedrock Edition game which contains super large amounts of machine translations, errrors, typos, wrongly picked terms and inconsistencies with JE (maybe especially in zh_CN since zh is one of the languages mostly shouldn't be translated by machine.) 

So I have taken an exploration through all translated zh_CN articles, finding that there's still lots of articles machine-translated without any post-edits. Even the titles looks in a mass. Moreover, even in those articles seemingly post-edited, MT errors and wrong terms can be seen everywhere. For example, in Chinese Simplified (China Mainland variant), Add-on should be 附加包 not 附加组件 or 加载项, tick (n.) be 刻 not 节拍, texture be 纹理 not 材质 (as similar as texture pack be 纹理包 not 材质包), material be 材质 not 材料, base be 基 not 基础 (for 基础 it's basic not base). Moreover, Minecraft the word shouldn't be translated as it's a brand name, and GameTest the word shouldn't be translated as it's a feature name, a proper noun, like JavaScript. Moreover, some MC-coined words are translated with inconsistency to community popularly/commonly used ones, like feature (in world generation) should be 地物 not 功能/特征, and volume (referred as a modding subject) should be 功能域 not 卷 (and it doesn't affect other words like volume fog 体积雾, volume light 体积光. Don't use the fucking "glossary find and replace" I am begging you!!!)

So after all, if the outsourcing translation team is still give so unsatisfactory translations, then in my opinion, it's better to let the community in like JE with Crowdin.
