### ISSUE TITLE
Error trying to convert a world

### ISSUE THREAD

**Issue by MadisonMadi** [MicrosoftDocs/minecraft-creator#526]
[Enter feedback here]
im trying to convert a world to java but i get this error after uploading
 
Oops, Failed to get world settings
Something went wrong while we were trying to grab the settings from the world, we were unable to recover from this error.

RESTART

Error identifier: 72f253d4115c4522bbeb9f3316ad5f1c

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 05710c2c-85f2-f8d1-1d96-2f91762ac20f
* Version Independent ID: 00b5b1f4-26d4-0a00-1362-b902458d0a9c
* Content: [Content Error Log](https://learn.microsoft.com/en-us/minecraft/creator/documents/contenterrorlog)
* Content Source: [creator/Documents/ContentErrorLog.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ContentErrorLog.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **mikeam**

**Comment by JimSeaman42** [comment]
Hi, thanks for reaching out! If you are having an issue attempting to upload your world, perhaps this document can help: https://learn.microsoft.com/en-us/minecraft/creator/documents/chunkeroverview

Otherwise, you may want to reach out to the Chunker team with your error code for assistance. I really hope that helps!
