### ISSUE TITLE
[Script API][Bug] Client Sync Issue

### ISSUE THREAD

**Issue by conmaster2112** [MicrosoftDocs/minecraft-creator#594]
Here I found a number of functions that are not synchronized with the client, the following methods are not synchronized with the client.

- **Permissions**
The change of OP status is changed on server side but client dont know about that, looks like you can still use commands, but u have no permission to do that. Following methods: 
  - [ ] **Player.prototype.setOp(...)**

- **Inventory APIs**
methods such as clearAll, clears the inventory but on client side player thinks he still have the items, updated after next interaction. Changing armor items on other entities doesn't render becouse items are not synced with client side as well.

  - [x] **Container.prototype.clearAll()**
  - [x] **Container.prototype.setItem(...)**
  - [x] **ContainerSlot.prototype.setItem(...)**
  - [x] **EntityEquipmentInventoryComponent.prototype.setEquipment(...)** 

- **Scoreboards Setter APIs**
The methods for changing that value in scoreboard doesnt update that values on displayed objectives in every display slots, such as (sidebar/list/belowname), value is not synced so clients things the value is still same, effected methods:
  - [ ] **ScoreboardObjective.prototype.setScore(...)**
  - [ ] **ScoreboardIdentity.prototype.setScore(...)**
  - [ ] **Scoreboard.prototype.setScore(...)**

All effects of these methods are not fully synced with client.

***Debug***
-Version: `Preview-v1.19.80.24`
-OS: `Win 11 Pro`
-Modules: [`@minecraft/server@1.2.0-beta`]

**Comment by McMelonTV** [comment]
bump

**Comment by ConsoleTerm** [comment]
# Inventory APIs
## Player Client
There is an issue with the deletion of itemStacks from a player’s inventory. This issue occurs when using the clearAll() method to delete the entire inventory or when using the setItem(undefined) and setEquipment(undefined) methods to delete individual slots. The deletion of items is not synchronized with the player, regardless of the method used.
## Entity
There is an issue with the synchronization between the client and server when it comes to equipment slots on entities. While everything related to the server works correctly, updates to the slots are not synchronized for the player. For example, if chest armor is added to a zombie using the API, the player will not see the armor because there was no synchronization between the client and server. This issue only concerns equipment slots and not the inventory. When an entity’s inventory is changed, the rendering does not change. *(That means it doesn't matter for inventory container, I think)*

**Comment by sereilly** [comment]
@ConsoleTerm this should be resolved as of 1.20.0.21. Thanks!

**Comment by ConsoleTerm** [comment]
> @ConsoleTerm this should be resolved as of 1.20.0.21. Thanks!
thanks for the reminder, I marked the inventory api's as closed
