### ISSUE TITLE
Something went wrong communicating with the server.

### ISSUE THREAD

**Issue by Kortrid** [MicrosoftDocs/minecraft-creator#855]
**Describe the bug**
Hi there,

So recently i have a problem when converting Java to Bedrock, when uploading the world always stuck at 36% and 72%. If I pass 36% everything is normal and if it is 72% it always fails to upload. It says that the server has an error with the Cloudflare code "502". This is very annoying and inefficient, if talking about the file its just 580MB, from what i know the maximum limit are 1GB.

I hope you can give me some informations about this problem. Thanks!

**To Reproduce**

**Expected behavior**
Sometimes the 'server' looks like stop uploading in 36% and 72%. If i pass the 36% and start upload again it will suddenly stop at 72% for no reason, then this message will pop up “ Something went wrong communicating with the server. ”

**Screenshots**
![IMG_20240604_103554](https://github.com/MicrosoftDocs/minecraft-creator/assets/171705398/c531b809-1320-4a4d-b605-06414734ef7e)

**Desktop (please complete the following information):**
 - OS:
 - Browser
 - Version

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10
 - OS: MIUI 12.5 (Global)
 - Browser Chrome
 - Version 125.0.6422.113

**Additional context**

**Comment by FormallyMyles** [comment]
Hi Kortrid,

We're not aware of any specific issues that should prevent you uploading this world, a few points that might be useful:
- The 1GB limit for Chunker is uncompressed, so if you're compressing your world you could be hitting the limit after it's uncompressed though given the error it's likely not this.
- Browsers can pause the connection if they sleep or tab out, so sometimes instability can be caused by this.
- VPNs / Proxies can also impact connection stability.

I did do a quick try myself with a 500mb world I had laying around on my phone with Chrome and didn't have any issues. If you're able to answer the following perhaps we can narrow down the issue:
- Are you using a VPN / Proxy?
- Are you use cellular data or Wi-Fi?
- What is your download and upload speed?
- How long does it take to get to 36 / 72 percent?

Thanks,
Myles

**Comment by Kortrid** [comment]
Q1. I didn't use any VPN
Uploading the file using cellular data
Q2. My download speed about 48Mbps, and the upload around 10-20Mbps
Q3. Around 20-40 seconds


For now, the problem looks like solved for no reason. Last night trying to upload again for the last time it works, and strangely i didn't encounter any problems like what i said earlier. My thoughts is just server overload, now the problem already solved. You can close this, if i encounters the same problem like this I'll tell you again
